# Generated by Django 4.0.5 on 2022-07-21 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boardApp', '0002_alter_article_author_alter_userresponse_author_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='UserResponse',
            new_name='Reply',
        ),
    ]
