# Generated by Django 4.0.5 on 2022-07-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardApp', '0003_rename_article_post_rename_userresponse_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='article',
            new_name='post',
        ),
    ]
